name: CI Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Write GAI_KEY to file
        run: |
          echo "${{ secrets.GAI_KEY }}" > gai-key.json
        shell: bash

      - name: Set GOOGLE_APPLICATION_CREDENTIALS env var
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gai-key.json" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint-fix

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build
