name: Build and deploy Node.js app to Azure Web App - MusicSchmusic

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install --workspaces=false
          npm run build --if-present
          npm run test --if-present
        working-directory: packages/express-backend

      - name: Zip artifact for deployment
        run: zip -r release.zip .
        working-directory: packages/express-backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: packages/express-backend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./artifact

      - name: Unzip artifact for deployment
        run: unzip ./artifact/release.zip -d deploy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C2E3E8972510461EB24F86EDF851A85D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0238147D1990490CA31ABF04483DFA4B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4FD602C273464DB9B470D95906A1FED4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MusicSchmusic'
          slot-name: 'Production'
          package: deploy
