name: Build and deploy Node.js app to Azure Web App - MusicSchmusic

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install all dependencies (root + packages)
        run: npm install

      - name: Build frontend
        run: npm run build
        working-directory: packages/react-frontend

      - name: Ensure backend build directory exists
        run: mkdir -p packages/express-backend/build

      - name: Copy frontend build into backend
        run: cp -r packages/react-frontend/dist/* packages/express-backend/build/

      - name: Run backend tests
        run: npm run test
        working-directory: packages/express-backend

      - name: Clean root node_modules
        run: rm -rf node_modules

      - name: Reinstall only production dependencies (workspace-aware)
        run: npm install --omit=dev

      - name: Zip backend with production node_modules
        run: |
          cd packages/express-backend
          zip -r ../../release.zip .

      - name: List ZIP contents for debug
        run: unzip -l release.zip

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./artifact

      - name: Unzip artifact
        run: unzip ./artifact/release.zip -d deploy

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C2E3E8972510461EB24F86EDF851A85D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0238147D1990490CA31ABF04483DFA4B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4FD602C273464DB9B470D95906A1FED4 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MusicSchmusic'
          slot-name: 'production'
          package: deploy
